version: "2"
linters:
  default: all
  disable:
    - canonicalheader
    - contextcheck
    - copyloopvar
    - cyclop
    - depguard
    - dupword
    - err113
    - errorlint
    - exhaustive
    - exhaustruct
    - forbidigo
    - forcetypeassert
    - funlen
    - gochecknoglobals
    - gochecknoinits
    - gocognit
    - goconst
    - gocyclo
    - godot
    - godox
    - gomoddirectives
    - inamedparam
    - interfacebloat
    - intrange
    - ireturn
    - lll
    - maintidx
    - makezero
    - mnd
    - nestif
    - nlreturn
    - noctx
    - nonamedreturns
    - paralleltest
    - protogetter
    - tagalign
    - tagliatelle
    - testpackage
    - thelper
    - varnamelen
    - wastedassign
    - wrapcheck
    - wsl
  settings:
    goconst:
      min-len: 2
      min-occurrences: 2
    gocritic:
      disabled-checks:
        - dupImport
        - ifElseChain
        - whyNoLint
        - sloppyReassign
        - uncheckedInlineErr
        - hugeParam
      enabled-tags:
        - diagnostic
        - experimental
        - opinionated
        - performance
        - style
    gocyclo:
      min-complexity: 15
    govet:
      disable:
        - fieldalignment
      enable-all: true
      settings:
        printf:
          funcs:
            - debug,debugf,debugln
            - error,errorf,errorln
            - fatal,fatalf,fataln
            - info,infof,infoln
            - log,logf,logln
            - warn,warnf,warnln
            - print,printf,println,sprint,sprintf,sprintln,fprint,fprintf,fprintln
    misspell:
      locale: US
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
