project_name: apm-lambda-extension

version: 2
before:
  hooks:
    - make check-licenses
    - make NOTICE.txt

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    flags:
      - -trimpath
    ldflags:
      - -s -w
    binary: "extensions/{{ .ProjectName }}"
    mod_timestamp: '{{ .CommitTimestamp }}'

archives:
  - id: zip
    formats: ['zip']
    name_template: |-
      {{ .Tag }}-{{ .Os }}-{{ .Arch }}
    files:
      - src: NOTICE.txt
        info:
          mtime: '{{ .CommitDate }}'
      - src: dependencies.asciidoc
        info:
          mtime: '{{ .CommitDate }}'
    builds_info:
      mtime: "{{ .CommitTimestamp }}"

dockers_v2:

  - &default-docker-image
    id: linux-amd64-image
    platforms:
      - 'linux/amd64'
    images:
      - '{{ .Env.DOCKER_REGISTRY }}/{{ .Env.DOCKER_IMAGE_NAME }}-x86_64'
    tags:
      - 'latest'
      - '{{ trimprefix .Tag "v" }}'
    labels:
      'org.opencontainers.image.created': '{{ .Date }}'
      'org.opencontainers.image.title': '{{ .ProjectName }}'
      'org.opencontainers.image.revision': '{{ .FullCommit }}'
      'org.opencontainers.image.version': '{{ .Version }}'
    build_args:
      'EXTENSION_FILE': 'linux/amd64/extensions/{{ .ProjectName }}'
      'COMMIT_TIMESTAMP': '{{ .CommitTimestamp }}'
    extra_files:
      - NOTICE.txt
      - dependencies.asciidoc

  - <<: *default-docker-image
    id: linux-arm64-image
    platforms:
      - 'linux/arm64'
    images:
      - '{{ .Env.DOCKER_REGISTRY }}/{{ .Env.DOCKER_IMAGE_NAME }}-arm64'
    tags:
      - 'latest'
      - '{{ trimprefix .Tag "v" }}'
    labels:
      'org.opencontainers.image.created': '{{ .Date }}'
      'org.opencontainers.image.title': '{{ .ProjectName }}'
      'org.opencontainers.image.revision': '{{ .FullCommit }}'
      'org.opencontainers.image.version': '{{ .Version }}'
    build_args:
      'EXTENSION_FILE': 'linux/arm64/extensions/{{ .ProjectName }}'
      'COMMIT_TIMESTAMP': '{{ .CommitTimestamp }}'

publishers:
  - name: publish-aws
    cmd: ./.ci/publish-aws.sh
    ids:
      - zip
    env:
      - AWS_ACCESS_KEY_ID={{ .Env.AWS_ACCESS_KEY_ID }}
      - AWS_SECRET_ACCESS_KEY={{ .Env.AWS_SECRET_ACCESS_KEY }}
      - AWS_SESSION_TOKEN={{ .Env.AWS_SESSION_TOKEN }}
      - ELASTIC_LAYER_NAME=elastic-apm-extension-ver-{{ replace (trimprefix .Tag "v") "." "-" }}
      - VERSION={{ .Tag }}
      - ARCHITECTURE={{ if eq .Arch "amd64" }}x86_64{{ else }}{{ .Arch }}{{ end }}
      - GOOS={{ .Os }}
      - GOARCH={{ .Arch }}
      - AWS_FOLDER=.aws-{{ .Os }}-{{ .Arch }}
release:
  # Custom GitHub release
  disable: true

# creates SBOMs of all archives and the source tarball using syft
# https://goreleaser.com/customization/sbom
sboms:
  - artifacts: archive

# Configure the checksums filename, to allow the GitHub attestation to pick up the correct filename
checksum:
  name_template: checksums.txt

docker_digest:
  name_template: "digests.txt"