:lambda-pull: https://github.com/elastic/apm-aws-lambda/pull/

////
[float]
[[lambda-x.x.x]]
==== x.x.x - YYYY/MM/DD

[float]
===== Breaking changes

[float]
===== Features
- Cool new feature: {lambda-pull}2526[#2526]

[float]
===== Bug fixes
////

[float]
[[lambda-unreleased]]
=== Unreleased

https://github.com/elastic/apm-aws-lambda/compare/v1.4.0...main[View commits]

[float]
===== Bug fixes
- Log a warning, instead of failing a Lambda function, if auth retrieval from AWS Secrets Manager fails. Reporting APM data will not work, but the Lambda function invocations will proceed. {lambda-pull}401[401]
- Fix incorrect proxy transaction handling at shutdown due to not flushing the data before processing shutdown event. {lambda-pull}412[412].

[float]
===== Features
- Use User-Agent header with Lambda extension version and propagate info from apm agents {lambda-pull}404[404]

[float]
[[lambda-1.4.0]]
=== 1.4.0 - 2023/05/03

https://github.com/elastic/apm-aws-lambda/compare/v1.3.1...v1.4.0[View commits]

[float]
===== Features
- experimental:[] Allow metadata in register transaction {lambda-pull}384[384]

[float]
[[lambda-1.3.1]]
=== 1.3.1 - 2023/04/04

https://github.com/elastic/apm-aws-lambda/compare/v1.3.0...v1.3.1[View commits]

[float]
===== Bug fixes
- Print response body on error if decoding fails {lambda-pull}382[382]

[float]
[[lambda-1.3.0]]
=== 1.3.0 - 2023/02/22

https://github.com/elastic/apm-aws-lambda/compare/v1.2.0...v1.3.0[View commits]

[float]
===== Features
- experimental:[] Create proxy transaction with error results if not reported by agent {lambda-pull}315[315]
- Wait for the final platform report metrics on shutdown {lambda-pull}347[347]
- Process platform report metrics when extension is lagging {lambda-pull}358[358]
- Add TLS support {lambda-pull}357[357]

[float]
[[lambda-1.2.0]]
=== 1.2.0 - 2022/11/01

[float]
===== Features
- Parse and log APM Server error responses, and backoff on critical errors {lambda-pull}281[281]
- Disable CGO to prevent libc/ABI compatibility issues {lambda-pull}292[292]
- Deprecate `ELASTIC_APM_DATA_RECEIVER_TIMEOUT_SECONDS` in favour of `ELASTIC_APM_DATA_RECEIVER_TIMEOUT` {lambda-pull}294[294]
- Log shutdown reason on exit {lambda-pull}297[297]
- Add support for collecting and shipping function logs to APM Server {lambda-pull}303[303]
- Batch data collected from lambda logs API before sending to APM Server {lambda-pull}314[314]

[float]
===== Bug fixes
- Fix possible data corruption while processing multiple log events {lambda-pull}309[309]

[float]
[[lambda-1.1.0]]
=== 1.1.0 - 2022/08/24

https://github.com/elastic/apm-aws-lambda/compare/v1.0.2...v1.1.0[View commits]


[float]
==== Features
- Added support for Secret Manager {lambda-pull}208[208]
- Added support for Lambda platform metrics {lambda-pull}202[202]
- Migrated to AWS SDK for Go v2 {lambda-pull}232[232]
- Make buffer size for agent data configurable {lambda-pull}262[262]
- Add support for reproducible builds {lambda-pull}237[237]
- Improve extension client error messages {lambda-pull}259[259]

[float]
==== Bug fixes
- Log a warning when authentication with APM Server fails {lambda-pull}228[228]
- Handle http.ErrServerClosed correctly {lambda-pull}234[234]
- Handle main loop errors correctly {lambda-pull}252[252]
- Avoid sending corrupted compressed data to APM Server {lambda-pull}257[257]
- Avoid creating http transports on each info request {lambda-pull}260[260]
- Randomise the initial grace period to avoid collisions {lambda-pull}240[240]
- Handle metadata errors correctly {lambda-pull}254[254]
- Always flush data to APM server before shutting down and avoid concurrent access to data channel {lambda-pull}258[258]

[float]
[[lambda-1.0.2]]
=== 1.0.2 - 2022/06/09

https://github.com/elastic/apm-aws-lambda/compare/v1.0.1...v1.0.2[View commits]

[float]
==== Bug fixes
- Only add executables to extension {lambda-pull}216[216]

[float]
[[lambda-1.0.1]]
=== 1.0.1 - 2022/06/03

https://github.com/elastic/apm-aws-lambda/compare/v1.0.0...v1.0.1[View commits]

[float]
==== Features
- Add support for building and pushing docker images {lambda-pull}199[199]

[float]
[[lambda-1.0.0]]
=== 1.0.0 - 2022/04/26

https://github.com/elastic/apm-aws-lambda/commits/46e65781912ca0448642e1574c1f8162ffa8dec0[View commits]

First stable release of the Elastic APM AWS Lambda extension.
