name: docs-cleanup

on:
  pull_request_target:
    types:
      - closed

jobs:
  docs-preview:
    uses: elastic/docs-builder/.github/workflows/preview-cleanup.yml@f04de82b8cb6f1400a60ff982478d31e4e1b5ae9 # main
    permissions:
      contents: none
      id-token: write
      deployments: write
