name: docs-cleanup

on:
  pull_request_target:
    types:
      - closed

jobs:
  docs-preview:
    uses: elastic/docs-builder/.github/workflows/preview-cleanup.yml@b133c9db88bc1d1bd83464bd6e275b010601f7af # main
    permissions:
      contents: none
      id-token: write
      deployments: write
