name: "Issue+PR Labeler"
on:
  issues:
    types: [opened]
  pull_request_target:
    types: [opened]

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
    - name: Get token
      id: get_token
      uses: actions/create-github-app-token@v2
      with:
        app-id: ${{ secrets.OBS_AUTOMATION_APP_ID }}
        private-key: ${{ secrets.OBS_AUTOMATION_APP_PEM }}
        permission-members: read
        permission-organization-projects: write
        permission-issues: read
    - name: Add aws-Î»-extension label
      uses: github/issue-labeler@c1b0f9f52a63158c4adc09425e858e87b32e9685 # v3.4
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        configuration-path: .github/labeler-config.yml
        enable-versioned-regex: 0
    - name: Check team membership for user
      uses: elastic/get-user-teams-membership@5fa8d08135326e44d74d0ec4ef8705d8e36df12d # 1.1.0
      id: checkUserMember
      with:
        username: ${{ github.actor }}
        team: 'observability'
        usernamesToExclude: |
          apmmachine
          dependabot
        GITHUB_TOKEN: ${{ steps.get_token.outputs.token }}
    - name: Show team membership
      run: |
        echo "::debug::isTeamMember: ${{ steps.checkUserMember.outputs.isTeamMember }}"
        echo "::debug::isExcluded: ${{ steps.checkUserMember.outputs.isExcluded }}"
    - name: Add community and triage labels
      if: steps.checkUserMember.outputs.isTeamMember != 'true' && steps.checkUserMember.outputs.isExcluded != 'true'
      uses: github/issue-labeler@c1b0f9f52a63158c4adc09425e858e87b32e9685 # v3.4
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        configuration-path: .github/community-label.yml
        enable-versioned-regex: 0
