name: snapshot

on:
  push:
    branches:
      - main
      - provenance
    paths-ignore:
      - "**/*.asciidoc"
      - "**/*.md"
      - "**/*.png"

env:
  DOCKER_BUILDKIT: 1
  DOCKER_REGISTRY: docker.elastic.co
  DOCKER_IMAGE_NAME: observability/apm-lambda-extension

permissions:
  contents: write
  id-token: write
  pull-requests: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
          check-latest: true

      - uses: docker/setup-qemu-action@v3
        with:
          platforms: linux/arm64, linux/amd64

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # See https://goreleaser.com/blog/supply-chain-security/
      - name: installs syft for generating the SBOM with goreleaser
        uses: anchore/sbom-action/download-syft@v0.15.10

      - name: Snapshot
        run: make dist

      - name: generate build provenance (binaries)
        uses: github-early-access/generate-build-provenance@main
        with:
          subject-path: "${{ github.workspace }}/dist/*.*"

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: snapshots
          path: "dist/*.*"
          retention-days: 5
